In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from modules.qr_code import QrCode, Measurement

# Loading data
camera_columns = ['timestamp', 'qr_code', 'cx', 'cy', 'width', 'height', 'distance', 'attitude']

qr_df = pd.read_csv('../data/qr_code_position_in_global_coordinate.csv')
camera_df = pd.read_csv('../data/task5/camera_localization_task5.csv', header=None, names=camera_columns)

In [3]:
# Setting up required QR codes' data for the task

qr_codes = []
for index, row in qr_df.iterrows():
    if row['position_in_wall'] == 2 and row['qr_code'] != 13:
        qr = QrCode(int(row['qr_code']), row['mid_point_x_cm'], row['mid_point_y_cm'])
        qr_codes.append(qr)

for qr in qr_codes:
    for index, row in camera_df.iterrows():
        if row['qr_code'] == qr.id:
            qr.add_measurement(Measurement(row['timestamp'], row['cx'], row['height']))

In [4]:
#Compute the variances of the measurements
for qr in qr_codes:
    qr.compute_variance()

In [5]:
from modules.localization import Localization

localization = Localization(h0=11.5, path="../data/task3/camera_module_calibration_task3.csv", qr_codes=qr_codes, distance_bias=6.7)

In [6]:
localization.R_inv.shape

(2, 2)

In [7]:
localization.localize()

qr code 15, 0 th iteration found a singular matrix
[[ 5.08647630e+04 -2.82357044e+01 -1.23906455e+04]
 [-2.82357044e+01  6.21831316e-01  6.92317035e+00]
 [-1.23906455e+04  6.92317035e+00  3.01836194e+03]]
qr code 15, 1 th iteration found a singular matrix
[[ 5.08647630e+04 -2.82357044e+01 -1.23906455e+04]
 [-2.82357044e+01  6.21831316e-01  6.92317035e+00]
 [-1.23906455e+04  6.92317035e+00  3.01836194e+03]]
qr code 15, 2 th iteration found a singular matrix
[[ 5.08647630e+04 -2.82357044e+01 -1.23906455e+04]
 [-2.82357044e+01  6.21831316e-01  6.92317035e+00]
 [-1.23906455e+04  6.92317035e+00  3.01836194e+03]]
qr code 15, 3 th iteration found a singular matrix
[[ 5.08647630e+04 -2.82357044e+01 -1.23906455e+04]
 [-2.82357044e+01  6.21831316e-01  6.92317035e+00]
 [-1.23906455e+04  6.92317035e+00  3.01836194e+03]]
qr code 15, 4 th iteration found a singular matrix
[[ 5.08647630e+04 -2.82357044e+01 -1.23906455e+04]
 [-2.82357044e+01  6.21831316e-01  6.92317035e+00]
 [-1.23906455e+04  6.923170