In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from modules.qr_code import QrCode, Measurement

# Loading data
camera_columns = ['timestamp', 'qr_code', 'cx', 'cy', 'width', 'height', 'distance', 'attitude']

qr_df = pd.read_csv('../data/qr_code_position_in_global_coordinate.csv')
camera_df = pd.read_csv('../data/task5/camera_localization_task5.csv', header=None, names=camera_columns)

In [3]:
# Setting up required QR codes' data for the task

qr_codes = []
for index, row in qr_df.iterrows():
    if row['position_in_wall'] == 2 and row['qr_code'] != 13:
        qr = QrCode(int(row['qr_code']), row['mid_point_x_cm'], row['mid_point_y_cm'])
        qr_codes.append(qr)

for qr in qr_codes:
    for index, row in camera_df.iterrows():
        if row['qr_code'] == qr.id:
            qr.add_measurement(Measurement(row['timestamp'], row['cx'], row['height']))

In [4]:
#Compute the variances of the measurements
for qr in qr_codes:
    qr.compute_variance()

In [5]:
from modules.localization import Localization

localization = Localization(h0=11.5, path="../data/task3/camera_module_calibration_task3.csv", qr_codes=qr_codes, distance_bias=6.7)

In [6]:
localization.R_inv

array([[ 4.386,  0.   ],
       [ 0.   , 21.739]])

In [7]:
localization.localize()

[-1.12124303e+04  4.62916176e+01  7.73925506e-04]
[625.20525569 100.84494373   1.27480155]
[ -3.71050067 -84.75551956 113.99009168]
[ -3.71050067 -84.75551956 113.99009168]
[ -3.71050067 -84.75551956 113.99009168]
[ -3.71050067 -84.75551956 113.99009168]
[ -3.71050067 -84.75551956 113.99009168]
[ -3.71050067 -84.75551956 113.99009168]
[ -3.71050067 -84.75551956 113.99009168]
[-7.55941827e+03  5.32888926e+01  1.28146478e-03]
[ 62.17123129 115.96953904   0.55806055]
[ 2.87034350e+01 -1.10259568e+02 -2.57343768e-02]
[ 2.87034350e+01 -1.10259568e+02 -2.57343768e-02]
[ 2.87034350e+01 -1.10259568e+02 -2.57343768e-02]
[ 2.87034350e+01 -1.10259568e+02 -2.57343768e-02]
[ 2.87034350e+01 -1.10259568e+02 -2.57343768e-02]
[ 2.87034350e+01 -1.10259568e+02 -2.57343768e-02]
[ 2.87034350e+01 -1.10259568e+02 -2.57343768e-02]
[-5.68437872e+03  6.13079210e+01  2.09436105e-03]
[-38.30210023 128.28598074   1.97236834]
[  -9.899701   -136.82706099   -1.6052094 ]
[  13.33386902 -135.37286529   -1.89478072]
[ 