In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from modules.qr_code import QrCode, Measurement

# Loading data
camera_columns = ['timestamp', 'qr_code', 'cx', 'cy', 'width', 'height', 'distance', 'attitude']

qr_df = pd.read_csv('../data/qr_code_position_in_global_coordinate.csv')
camera_df = pd.read_csv('../data/task5/camera_localization_task5.csv', header=None, names=camera_columns)

In [3]:
# Setting up required QR codes' data for the task

qr_codes = []
for index, row in qr_df.iterrows():
    if row['position_in_wall'] == 2 and row['qr_code'] != 13:
        qr = QrCode(int(row['qr_code']), row['mid_point_x_cm'], row['mid_point_y_cm'])
        qr_codes.append(qr)

for qr in qr_codes:
    for index, row in camera_df.iterrows():
        if row['qr_code'] == qr.id:
            qr.add_measurement(Measurement(row['timestamp'], row['cx'], row['height']))

In [4]:
#Compute the variances of the measurements
for qr in qr_codes:
    qr.compute_variance()

In [5]:
from modules.localization import Localization

localization = Localization(h0=11.5, path="../data/task3/camera_module_calibration_task3.csv", qr_codes=qr_codes, distance_bias=6.7)

In [6]:
localization.R_inv.shape

(2, 2)

In [7]:
localization.localize()

[[ 2.44041373e+05 -9.19888280e+01 -5.67066224e+04]
 [-9.19888280e+01  7.32949223e-01  2.14083478e+01]
 [-5.67066224e+04  2.14083478e+01  1.31766240e+04]]
[-5.53901815e+06  2.12655706e+03  1.28707464e+06]
[[ 8.45773691e+04 -1.94073220e+00  1.61663690e+03]
 [-1.94073220e+00  2.09799864e-03 -3.70906985e-02]
 [ 1.61663690e+03 -3.70906985e-02  3.09008769e+01]]
[-6.82365629e+03 -5.44982554e+00 -1.30443127e+02]
[[ 8.45773691e+04 -1.94073220e+00  1.61663690e+03]
 [-1.94073220e+00  2.09799864e-03 -3.70906985e-02]
 [ 1.61663690e+03 -3.70906985e-02  3.09008769e+01]]
[-6.82365629e+03 -5.44982554e+00 -1.30443127e+02]
[[ 8.45773691e+04 -1.94073220e+00  1.61663690e+03]
 [-1.94073220e+00  2.09799864e-03 -3.70906985e-02]
 [ 1.61663690e+03 -3.70906985e-02  3.09008769e+01]]
[-6.82365629e+03 -5.44982554e+00 -1.30443127e+02]
[[ 8.45773691e+04 -1.94073220e+00  1.61663690e+03]
 [-1.94073220e+00  2.09799864e-03 -3.70906985e-02]
 [ 1.61663690e+03 -3.70906985e-02  3.09008769e+01]]
[-6.82365629e+03 -5.44982554e+

LinAlgError: Singular matrix